version: '3.8'


configs:
   internalConfig:
     external: true
     name: apacheHttpsRedirections

services:
  apache:
    image: rcgcoder/apache2servercontainer:arm64
    environment:
        - withUser=oneUser
        - withPassword=onePassword
        - TimeZone=oneTimeZone
        - withMail=onemail@mail.com
        - withDomain=onedomain.com
        - withTestingCertificate=false
        - withSecretCertificate=true
    configs:
      - source: internalConfig 
        target: /usr/configs/apache2/httpsRedirections.conf
    ports:
      - "8443:443"
      - "8080:80"
    deploy:
      replicas: 1
    secrets:
      - sslKey
      - sslPem

secrets:
   sslKey:
     external: true
   sslPem:
     external: true
